#!/usr/bin/env bash

additional_args=""

IFS= read -p "plugin type (f/k/r/w) [default: f (filter)]: " type
if [[ -z "$type" ]]; then type="f"; fi

case "$type" in
("f") type="filter" ;;
("k") type="kernel" ;;
("r") type="reader" ;;
("w") type="writer" ;;
 (*)  echo "$type is an unsupported option, choose (f/k/r/w)"
      exit 1 ;;
esac

if [[ "$type" != "filter" ]]; then echo "only filters are supported at this time"; exit 1; fi


IFS= read -p "$type name: " name
if [[ -z "$name" ]]; then echo "name required"; exit 1; fi

IFS= read -p "output directory [default: /tmp/$name]: " target_dir
if [[ -z "$target_dir" ]]; then target_dir="/tmp/$name"; fi

IFS= read -p "$type namespace [default: none]: " ns

IFS= read -p "enable matlab support [y/n]: " with_matlab
if [[ "$with_matlab" == "y" ]]; then
  additional_args="$additional_args -DWITH_MATLAB=ON"
fi

echo ""

readonly src_dir="$PWD"
readonly build_dir="$target_dir/cmake-build-scaffolding"

echo "scaffolding from $build_dir ..."
echo "type: $type"
echo "name: $name"
echo "namespace: $ns"
echo "destination: $target_dir"
echo "additional args: $additional_args"

mkdir -p "$build_dir"
cd "$build_dir"
cmake "$src_dir" -DPLUGIN_TYPE="$type" -DPLUGIN_NAME="$name" -DPLUGIN_NAMESPACE="$ns" -DTARGET_DIR="$target_dir" $additional_args

IFS= read -p "initialize conan for clion [y/n]: " init_conan
if [[ "$init_conan" == "y" ]]; then
 conan install "$target_dir" -s build_type=Debug --install-folder="$target_dir"/cmake-build-debug
fi

echo "scaffolding complete, $build_dir can be deleted"

echo "initializing repo"
cd "$target_dir"

git init > /dev/null
git commit --allow-empty -m "initialize repository" > /dev/null
git add . > /dev/null
git commit -m "initialize project" > /dev/null

cd "$src_dir"

echo "$name has been created in $target_dir"
