#!/usr/bin/env bash

readonly src_dir="$PWD"
additional_args=""

if [[ -z $(git config --get user.name) ]] || [[ -z $(git config --get user.email) ]]; then
  echo "global git user and email must be configured prior to scaffolding"
  exit 1;
fi

IFS= read -p "plugin type [F/k/r/w]: " type
if [[ -z "$type" ]]; then type="f"; fi

case "${type,,}" in
  ("f") type="filter" ;;
  ("k") type="kernel" ;;
  ("r") type="reader" ;;
  ("w") type="writer" ;;
   (*)  echo "$type is an unsupported option, choose (f/k/r/w)"
        exit 1 ;;
esac

if [[ "$type" != "filter" ]]; then echo "only filters are supported at this time"; exit 1; fi


IFS= read -p "$type name: " name
if [[ -z "$name" ]]; then echo "name required"; exit 1; fi

IFS= read -p "$type description: " desc

IFS= read -p "output directory [/tmp/$name]: " target_dir
if [[ -z "$target_dir" ]]; then target_dir="/tmp/$name"; fi

IFS= read -p "cxx standard [(11)/14/17]: " cxx_in
if [[ -z "$cxx_in" ]]; then cxx_in="11"; fi

for s in "11" "14" "17"; do if [[ "$cxx_in" == "$s" ]]; then cxx="$cxx_in"; fi; done
if [[ -z "$cxx" ]]; then echo "$cxx_in is not a valid cxx standard"; exit 1; fi

IFS= read -p "$type namespace [none]: " ns

IFS= read -p "external conanfile [None/t]: " with_conanfile
# look away ...
if [[ ! -z "$with_conanfile" ]]; then
  case "$with_conanfile" in
    ("t") with_conanfile="$src_dir/conanfile.py.template" ;;
    ("T") with_conanfile="$src_dir/conanfile.py.template" ;;
    ("none") with_conanfile="" ;;
    ("None") with_conanfile="" ;;
    ("n") with_conanfile="" ;;
    ("N") with_conanfile="" ;;
     (*)  ;;
  esac

  if [ ! -f "$with_conanfile" ]; then echo "$with_conanfile not found."; exit 1; fi
  additional_args="$additional_args -DCONANFILE=$with_conanfile"
fi

IFS= read -p "enable matlab support [y/N]: " with_matlab
if [[ "${with_matlab,,}" == "y" ]]; then
  additional_args="$additional_args -DWITH_MATLAB=ON"
fi

IFS= read -p "initialize conan for clion [y/N]: " init_conan

echo ""

readonly build_dir="$target_dir/cmake-build-scaffolding"

echo "Scaffolding options"
echo "==================="
echo "type: $type"
echo "name: $name"
echo "description: $desc"
echo "namespace: $ns"
echo "cxx standard: $cxx"
echo "destination: $target_dir"
echo "clion conan init: $init_conan"
echo "plugin version: 1.0.0"
echo "additional args: $additional_args"

echo ""

read -p "press enter to perform scaffolding... "

mkdir -p "$build_dir"
cd "$build_dir"
cmake \
-DPLUGIN_TYPE="$type" \
-DPLUGIN_NAME="$name" \
-DPLUGIN_NAMESPACE="$ns" \
-DTARGET_DIR="$target_dir" \
-DCXX_STANDARD="$cxx" \
-DPLUGIN_DESCRIPTION="$desc" \
$additional_args \
"$src_dir" > /dev/null

if [[ "${init_conan,,}" == "y" ]]; then
 conan install "$target_dir" -s build_type=Debug --install-folder="$target_dir/cmake-build-debug" > /dev/null
 echo ""
 echo "Conan initialized in "$target_dir/cmake-build-debug""
fi

cd "$target_dir"

git init > /dev/null
git commit --allow-empty -m "initialize repository" > /dev/null
git add . > /dev/null
git commit -m "initialize project" > /dev/null
git tag -a -m "initialized" v0.0.0

cd "$src_dir"

echo ""
echo "scaffolding complete, $build_dir can be deleted"
