#!/usr/bin/env bash

IFS= read -p "plugin type [f/k/r/w]: " type

IFS= read -p "$type name: " name
if [[ -z "$name" ]]; then echo "name required"; exit 1; fi

IFS= read -s -p "output directory (default /tmp/$name): " target_dir
if [[ -z "$target_dir" ]]; then target_dir="/tmp/$name"; fi

echo ""

readonly src_dir=$PWD
readonly build_dir="$target_dir/cmake-build-scaffolding"

echo "scaffolding from $build_dir ..."
echo "type: $type"
echo "name: $name"
echo "destination: $target_dir"

mkdir -p "$build_dir"
cd "$build_dir"
cmake "$src_dir" -DPLUGIN_TYPE=filter -DPLUGIN_NAME="$name" -DTARGET_DIR="$target_dir"
cd "$src_dir"

echo "scaffolding complete, $build_dir can be deleted"
