#!/usr/bin/env bash

readonly srcdir="$PWD"
readonly name="cmake-build-MyPlugin"
readonly root="$srcdir/$name"

rm -rf "$root"

mkdir -p "$root/build"
mkdir -p "$root/scaffolding"

cd "$root/scaffolding"

cmake \
-DPLUGIN_TYPE="filter" \
-DPLUGIN_NAME="MyPlugin" \
-DPLUGIN_NAMESPACE="jw3" \
-DTARGET_DIR="$root" \
-DCXX_STANDARD="14" \
-DMAJOR_VERSION=1 \
-DMINOR_VERSION=0 \
-DPATCH_VERSION=0 \
"$srcdir" > /dev/null

cd "$root/build"
pwd
conan install "$root"
cmake "$root"
make

if [[ ! -z $(PDAL_DRIVER_PATH="$root/build/lib" pdal --drivers | grep jw3_MyPlugin) ]]; then
  echo "Success!"
  exit 0;
else
  echo "Failure!"
  exit 1;
fi
